buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.4.0-alpha04'
    }
}

tasks.whenTaskAdded { task ->
    if (task.name.equals("lint")) {
        task.enabled = false
    }
}

apply plugin: 'android'
apply plugin: 'com.android.application'

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation 'androidx.core:core:1.19.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.squareup.okhttp3:okhttp:4.2.2'
    implementation 'com.google.android.material:material:1.3.0-alpha02'
    implementation 'com.google.android.gms:play-services-location:20.0.0'
    implementation 'com.google.android.gms:play-services-tasks:18.0.1'
    // do not use this in your code, but necessary for the (old) smtp mailer
    // implementation 'org.apache.httpcomponents:httpclient:4.5.13'
    // implementation 'org.apache.httpcomponents:httpcore:4.4.14'
    // implementation 'com.sun.mail:javax.mail:1.6.1'
    // implementation 'com.sun.mail:android-activation:1.6.7'
    // migrate to jakarta mail
    // implementation 'jakarta.mail:jakarta.mail-api:2.1.3'
    // implementation 'org.eclipse.angus:angus-mail:2.0.3'
    implementation 'com.sun.mail:jakarta.mail:2.0.1'
    implementation fileTree(include: ['*.jar'], dir: 'libs')
}

android {
    compileSdkVersion 37
    useLibrary 'org.apache.http.legacy'
    namespace 'tv.giss.emercam'

    defaultConfig {
        applicationId "tv.giss.emercam"
        minSdkVersion 23
        targetSdkVersion 37
        versionCode = 29
        versionName = "2.9"
        multiDexEnabled true
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDir 'libs'
        }
    }

    signingConfigs {
        release {
            storeFile file("emercam.jks")
            storePassword "cam888"
            keyAlias "emercam"
            keyPassword "cam888"
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-android.txt'
        }
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 
                         'META-INF/LICENSE', 
                         'META-INF/LICENSE.txt', 
                         'META-INF/license.txt', 
                         'META-INF/LICENSE.md',
                         'META-INF/mimetypes.default',
                         'META-INF/mailcap.default',
                         'META-INF/NOTICE', 
                         'META-INF/NOTICE.txt', 
                         'META-INF/NOTICE.md', 
                         'META-INF/notice.txt']
        }
    }


    lint {
        abortOnError false
        checkReleaseBuilds false
    }

}
